### ISSUE TITLE
'@vaadin/vaadin-lumo-styles/badge' could be found. Module ignored

### ISSUE THREAD

**Issue by sascha-frinken** [devsoap/ds-gradle-vaadin#302]
**Desktop (please complete the following information):**
 - OS: Linux
 - JDK version: 11
 - Gradle version: 5.6.2
 - Vaadin Plugin version: 1.3.beta5

**Describe the bug**
Having follwoing `JsModule` annotation `@JsModule("@vaadin/vaadin-lumo-styles/badge")` produces following warning: `No Javascript module with the name '@vaadin/vaadin-lumo-styles/badge' could be found. Module ignored.`   
Using latest Vaadin Business Starter App…

**Comment by johndevs** [comment]
This error means you are missing the ``@vaadin/vaadin-lumo-styles`` NPM dependency. 
You should be able to add it manually via 
```
vaadinClientDependencies {
       yarn '@vaadin/vaadin-lumo-styles'
}
```
Since the Vaadin Business Starter is a commercial Vaadin product and not open source I can't really help you further. You might want to turn to the Vaadin guys for help.

**Comment by johndevs** [comment]
I think you have a typo, the ``.js`` extension is missing. 

So it should be ``@JsModule("@vaadin/vaadin-lumo-styles/badge.js")``

**Comment by sascha-frinken** [comment]
The orginal vaadin source has no `.js` extension.  
I already tried with `@JsModule("@vaadin/vaadin-lumo-styles/badge.js")` that makes the warning disappear but the style is not applied…  

Looks like some magic.

**Comment by johndevs** [comment]
Looks like the badge styles are problematic. Found at least these tickets about them:
- https://github.com/vaadin/vaadin-lumo-styles/issues/75 
- https://github.com/vaadin/vaadin-lumo-styles/issues/17

**Comment by johndevs** [comment]
Tested this with the latest master branch and was successful in using the badge style by using the following approach:

1. Include the badge style when importing your theme:
```java
@CssImport(value = "./theme.css", include = "lumo-badge")
```
2. Import the badge javascript
```java
@JsModule("@vaadin/vaadin-lumo-styles/badge.js")
```
3. Set the **theme**-attribute of the element. For example like this:
```java
  Html html = new Html("<span>Badge</span>");
  html.getElement().setAttribute("theme", "badge");
```
This will yield the following badge:
![](https://user-images.githubusercontent.com/1967917/73290800-bbbab080-4207-11ea-9900-c5332a96ee24.png)



Most likely this got solved when adding the missing attribute support for ``@CssImport`` in #321
