### ISSUE TITLE
Starters

### ISSUE THREAD

**Issue by johndevs** [devsoap/ds-gradle-vaadin#73]
This involves doing the following:
- Create a few lazybones Vaadin starters using the plugin and deploy them to lazybones
- Create a page listing all the starters somewhere (github.io/devsoap.com)

**Comment by johndevs** [comment]
Beverage buddy added to https://github.com/devsoap/examples/tree/master/beverage-starter-flow-gradle

**Comment by thekaratekid05** [comment]
@johndevs Hi...great plugin btw! Its been much more of a help than the maven counterpart.

With Vaadin 7/8 us Java devs were pretty much able to get up any running with a few jars and jetty, But as you know Vaadin 10+ is a whole different kettle of fish!

This plugin certainly helps someone getting a working example up and running...but as a newbie I'm still a bit baffled by all the npm/yarn/bower/webjar/polymer/gulp magic that is going on behinds the scene.

Getting a project up an running in a corporate environment is even more tricky given that most would need to be in full control of external dependencies and anything that reaches outside the building.

It might help if there was a bit more 'starter' documentation on what the plugin does and where it puts files after each step i.e. get webjars, get npm dependencies, get yarn dependencies, unpack bower structure,  run polymer, minify java script etc...

Also i'm still trying to get my head around npm vs yarn...why do we need to use both? Don't they do roughly the same thing?
